# Use official Python image
FROM python:3.10-slim

# Environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory in container
WORKDIR /app

# Copy requirements and install
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project code
COPY . /app/

# Run Django using gunicorn
CMD ["gunicorn", "onlinetechshop.wsgi:application", "--bind", "0.0.0.0:8000"]
